In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('indian_bus_fare_sample.csv')

In [3]:
df.shape

(100, 8)

In [4]:
df.sample(5)

,Agency,Source,Destination,Bus Type,Travel Date,Fare Price (INR),Total Seats,Duration (hours)
44,Parveen Travels,Lucknow,Jaipur,Sleeper,2018-12-20,2094.62,33,15.1
29,SRS Travels,Ahmedabad,Delhi,Luxury,2020-05-14,1980.22,41,19.9
1,KPN Travels,Mumbai,Pune,Luxury,2018-01-29,1068.56,41,6.2
48,Sharma Travels,Chennai,Pune,Sleeper,2017-10-10,1454.83,51,10.0
63,VRL Travels,Mumbai,Hyderabad,AC Seater,2019-01-19,2950.39,55,10.1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Agency            100 non-null    object
 1   Source            100 non-null    object
 2   Destination       100 non-null    object
 3   Bus Type          100 non-null    object
 4   Travel Date       100 non-null    object
 5   Fare Price (INR)  100 non-null    float64
 6   Total Seats       100 non-null    int64
 7   Duration (hours)  100 non-null    float64
dtypes: float64(2), int64(1), object(5)
memory usage: 6.4+ KB

In [6]:
df.isnull().sum()

Agency              0
Source              0
Destination         0
Bus Type            0
Travel Date         0
Fare Price (INR)    0
Total Seats         0
Duration (hours)    0
dtype: int64

In [7]:
df.describe()

       Fare Price (INR)  Total Seats  Duration (hours)
count        100.000000   100.000000        100.000000
mean        1659.527900    41.830000         11.981000
std          771.923596     7.587942          4.831665
min          342.270000    30.000000          4.100000
25%          984.072500    35.000000          8.150000
50%         1741.600000    41.000000         11.150000
75%         2299.935000    48.000000         16.650000
max         2968.720000    55.000000         19.900000

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.corr(numeric_only=True)['Total Seats']

Fare Price (INR)    0.119749
Total Seats         1.000000
Duration (hours)    0.011317
Name: Total Seats, dtype: float64